### ISSUE TITLE
Ensure the public URL is not indexed

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework-scheduler#8]
Turn off URL crawling by using X-Robots-Tag

See: https://developers.google.com/search/reference/robots_meta_tag
See: https://support.joomlatools.com/tickets/topic/9780
See: https://support.joomlatools.com/tickets/topic/10052

**Comment by johanjanssens** [comment]
@ercanozkaya Has this been included in the new framework release?
